### ISSUE TITLE
Tab not working

### ISSUE THREAD

**Issue by hinaloe** [deconf/Google-Analytics-Dashboard-for-WP#10]
After update to 4.5, all tabs in setting of  this plugin is not  working.
 ![](http://puu.sh/gNTYQ/97eec8c600.png)

**Comment by deconf** [comment]
Press CTRL+F5 to refresh the page or clear your browser cache. For support use https://deconf.com/ask/, use github to report bugs!

**Comment by hinaloe** [comment]
I'd retry with super reload...but not working too, any browser, any
devices, and any site.

Isn't this a bug?

*Note: There is no log on console.*

**Comment by deconf** [comment]
Can you delete the mo file for your translation, you can find it under wp-content/plugins/google-analytics-dashboard-for-wp/languages? It may be a translation issue.

**Comment by hinaloe** [comment]
Thanks, that's right.

**Comment by deconf** [comment]
It's the Japanese translation, right?

**Comment by hinaloe** [comment]
Yes, and I found where the bug.

in [`load_styles_scripts`](https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/master/admin/setup.php#L128), `$hook`'s strig is made with useing `__("Google Analytics", 'ga-dash')` like `google-%e3%82%a2%e3%83%8a%e3%83%aa%e3%83%86%e3%82%a3%e3%82%af%e3%82%b9%e8%a7%a3%e6%9e%90_page_gadash_tracking_settings`.

so [`wp_enqueue_script`](https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/master/admin/setup.php#L239-L249) is not work.

**Comment by deconf** [comment]
I've removed translation for that string and released 4.5.1, you should check that out.

**Comment by hinaloe** [comment]
Thanks! that worked fine!
