### ISSUE TITLE
View switches back to default every few days

### ISSUE THREAD

**Issue by wrooot** [deconf/Google-Analytics-Dashboard-for-WP#100]
I have already posted this on twitter. You mentioned this can be because of cookies or updates. Well, there was no Firefox or add-on update for 2 days. There was no GADWP update also. I don't clear cookies myself. Yesterday it was fine (i set it to Yesterday - Pages (pages button) usually). Today it switched back to Last 30 days - Sessions. What else can i provide to debug this? I see 3 cookies for gadwp and they all set to expire on July 1. Default_swmetric, default_metric, default_dimension. Their content values are pageviews, contentpages, yesterday. It seems that these cookies are saving the view. Expiration period for them is too small.

**Comment by deconf** [comment]
I've increased the expiration time from 7 days to 365 days. Thanks for the feedback!

**Comment by wrooot** [comment]
Thanks
