### ISSUE TITLE
Show User's analytics within respective user's account

### ISSUE THREAD

**Issue by PrasadDiwan** [deconf/Google-Analytics-Dashboard-for-WP#104]
Recently I came across a scenario where I had to display No. of Post Views, Avg. Session Duration for the posts written by that user only. e.g. I have two authors who write for my blog. I wanted to show each user with their respective statistics data i.e. No. of Post Views, Avg. Session Duration which can be filtered out datewise.
I was using this plugin but there was no such way to achieve this functionality.
It might be helpful to people if it is provided with the plugin.
Is there a way to achieve this?

**Comment by deconf** [comment]
The plugin does provide ways to track authors as a custom dimension. Furthermore, custom reports can be created to display the required data on analytics.google.com. Unfortunately, this feature is not available on WordPress dashboard reports, at this moment.
