### ISSUE TITLE
WP GAD 5.1.1.3, Exponential Back Off - Isn't backing off enough!

### ISSUE THREAD

**Issue by KBCoggin** [deconf/Google-Analytics-Dashboard-for-WP#105]
I have WP Google Analytics 5.1.1.3 and all of a sudden I am seeing the following error:
(403) Quota Error: Number of recent failed reporting API requests is too high, please implement exponential back off.
I have tried several times to re-auth the plugin, but it isn't helping.  I cannot see real-time.  What can I do to fix this?

**Comment by deconf** [comment]
Hi,
Can you give some details about your setup (are you running a network, how many people have access to your stats, do you use your own API Project?).

Normally, under normal circumstances you shouldn't reach such a threshold

**Comment by KBCoggin** [comment]
Alin,
I am running it only on my website.  2 users have access, myself and my CEO.  I am not using any API, just your plugin.  I had my MailChimp accessing the Google Analytics data too, but I have disconnected it thinking that might be part of the problem. 

Kenneth Coggin
COO
DIY E-liquid Supplies
310-242-0635

**Comment by deconf** [comment]
Can you post all the data displayed on the Errors & Debug screen. I think something has changed on the Real-Time API or there is a bug on the plugin because I've noticed a big error increase on this component lately. I personally was unable to replicate it, so please try to provide as much details as possible. For the begging the exact errors will help.

Thanks again!

**Comment by KBCoggin** [comment]
I think it was an error on their system.  Just checked and it is working again, but is now tracking Desktop vs Mobile!  SO COOL!  Thank you for your concerns though! Kenneth CogginChief Operating OfficerDIY E-liquid Supplies310-242-0635On October 4, 2017 at 7:25 AM Alin Marcu <notifications@github.com> wrote:Can you post all the data displayed on the Errors & Debug screen. I think something has changed on the Real-Time API or there is a bug on the plugin because I've noticed a big error increase on this component lately. I personally was unable to replicate it, so please try to provide as much details as possible. For the begging the exact errors will help.Thanks again!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
