### ISSUE TITLE
Access Code doesn't saved

### ISSUE THREAD

**Issue by emira** [deconf/Google-Analytics-Dashboard-for-WP#107]
Hi !

I have a really odd bug with plugin authorization : I can get the access code, paste it in the field and click on the button "save access code" then i land on the success page. So far so good.
But when I reload the page (or save the settings or when i go to another page), the access code is "forgotten", as if I had never input and saved it.
I already have deactivated all plugins, to prevent a conflict, but no results.

**Comment by deconf** [comment]
Can you check if there are any errors displayed under **Google Analytics -> Errors & Debug** screen from your administration area?

Also, try to use a Private/Incognito browser window during authorization, to make sure no browser extensions are disturbing the authorization process (mainly privacy extensions or AdBlockers).

**Comment by emira** [comment]
Thanks for the reply.

There are no error or bug detected in "Error & Debug" screen ( Last Error detected > Last Error: None  /  Error Details > Error Details: None).
And even with private session or with Safari the bug persisted.

**Comment by deconf** [comment]
Please check your PHP error log for possible related errors; otherwise try to reinstall the plugin.

**Comment by emira** [comment]
I have a PHP error which is very persistant : 
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'wphead_cb' not found or invalid function name in /home/valdiserrq/www-valdisere/wp-includes/class-wp-hook.php on line 298

I'm looking for a solution since a few days but no relevant result for now... And I don't even know if it's connected with the plugin problem

**Comment by deconf** [comment]
Hi again,

Have you tried to temporarily switch to a default theme and see how it goes. The warning seems to be generated by your theme.

**Comment by emira** [comment]
Hi !
I succeed to resolve all PHP errors (and JS too) but the problem is still here ...
I really don't understand :/

**Comment by emira** [comment]
I have a question : my website runs on PHP 7, could it be the source of the problems i'm encountering ?

**Comment by deconf** [comment]
No,

GADWP is fully compatible with PHP 7.  

Have you tried reinstalling the plugin as suggested above?

Otherwise it could be a server configuration issue, because it seems like the plugin doesn't manage to save the value on your database.
