### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by KrzysiekF** [deconf/Google-Analytics-Dashboard-for-WP#110]
Hello,
Thank you for your great work! This plugin is realy nice.

I have a question. How can I add custom event? I wont to add somthing like this:

`ga('send', 'event', 'Videos', 'play', 'Fall Campaign');`

This is only example.

Thank you!

**Comment by Nodws** [comment]
Same, we need an "Events" view on the dropdown menu.

In the mean while you can take a look at Custom dimensions 
```
ga('send', 'event', 'Videos', 'play', {
  'metric1': 'Fall Campaign'
});
```

**Comment by deconf** [comment]
See https://gist.github.com/deconf/41c8fd568423ddbd9e70.

**Comment by Nodws** [comment]
Well yeah we can send events, but how do we view the report on the dashboard or individual page?
also where do we view the other integrated events? (phone, outbound, affiliate, etc)

**Comment by deconf** [comment]
All events are available on analytics.google.com at the moment. Due to the limited size of the widget it's difficult to display meaningful reports on events.

**Comment by Nodws** [comment]
Yep, already wrote a script for this, will see if I can integrate it and push something ;)
