### ISSUE TITLE
Tracks sent emails and shoe "/emails/anmerkung-des-kunden" under URL

### ISSUE THREAD

**Issue by Tobias-Conrad** [deconf/Google-Analytics-Dashboard-for-WP#115]
Hello i use the free plugin to track opened and clicked mails:
https://de.wordpress.org/plugins/email-tracker/

Your plugin or the woo GA PLG (https://de.wordpress.org/plugins/woocommerce-google-analytics-integration/)

show "/emails/anmerkung-des-kunden" in the visited URL.

"/emails/anmerkung-des-kunden" = emails/notice to customer

i deactivated woo GA plugin once inside plugin and the "/emails/anmerkung-des-kunden" is gone.
May please add more compatibility to this two plugins.

Thanks.

**Comment by deconf** [comment]
Hi,

Can you explain what exactly ave you deactivated? The WooCommerce Google Analytics Integration plugin or an option o it?
