### ISSUE TITLE
Feature Request: Add 4th mode for Multisite

### ISSUE THREAD

**Issue by smhosting** [deconf/Google-Analytics-Dashboard-for-WP#116]
It would be great if a fourth mode could be added for Multisite: Network Activated using a single account plus multiple accounts for subsites.

I use Multisite with domain mapping frequently; tracking both traffic to the entire network with one account and individual sites with their unique accounts. Currently, I use GADWP for the entire network and then add separate codes for each subsite in their headers. It would be great if this could be done with one plugin in order to save futzing around creating code for all the custom dimensions and other goodies.

**Comment by deconf** [comment]
Hi,

I would rather use an opposite approach. Use the plugin for individual tracking and add the network wide tracking code on the head automatically (for example making use of mu-plugins).
