### ISSUE TITLE
Plugin not using WP_PROXY_* definitions

### ISSUE THREAD

**Issue by asrenzo** [deconf/Google-Analytics-Dashboard-for-WP#121]
Hi,
My wordpress is behind a proxy with authentication. Adding WP_PROXY_* constants to wp-config.php allows me to update plateform and plugins.
But GADWP does not use these definitions to configure his own curl requests with these values.

I've seen the : $curl_options = apply_filters( 'gadwp_curl_options', $curl_options ); line in tools/gapi.php but as gadwp_curl_options is not defined anywhere else in plugin I don't think this has any effect.

Maybe I'm missing something but I guess GADWP should use global definitions.

If not could you tell me where and how I should configure these values for GADWP ?

Regards

**Comment by kuiperr005** [comment]
I'm having the exact same issue here. How can we use those options?

**Comment by deconf** [comment]
Hi, make sure that PHP cURL is enabled and follow this setup https://developer.wordpress.org/reference/classes/wp_http_proxy/.

**Comment by deconf** [comment]
The feature is supported in GADWP 5.2+.

**Comment by kuiperr005** [comment]
I am using version 5.2.2 but the authorization process for the plugin to work does not seem to use the proxy, is that right?

**Comment by deconf** [comment]
If you are sure, it must be a bug. Open a new issue giving as much details as possible.

**Comment by kuiperr005** [comment]
Ok, I opened an issue here #128
