### ISSUE TITLE
Button submit not tracked

### ISSUE THREAD

**Issue by tsager** [deconf/Google-Analytics-Dashboard-for-WP#124]
Hi,

I am using wpdevart forms on my page and am not receiving the form events even though I have activated it in the configuration.

Might this be due to the fact that the form is using a button instead an input tag?
http://tifico.ch/cd-bestellung/

Thanks, Tobias

**Comment by deconf** [comment]
Hi,

As the name of the feature suggests, it requires a form submit action to work.

**Comment by tsager** [comment]
There is a form, however no input/submit, but a button with a JS submit. Shouldn't the Ajax form tracking work in this case?

**Comment by tsager** [comment]
Hi @deconf, I was wondering if using both input[type="submit"] and button[type="submit"] in gadwpUAEventsData.options.event_formsubmit would allow tracking the button events as well?

**Comment by deconf** [comment]
GADWP 5.3 will support button[type="submit"].
