### ISSUE TITLE
BUG - Stats for one specific posts as (NOT SET)

### ISSUE THREAD

**Issue by leafarblur** [deconf/Google-Analytics-Dashboard-for-WP#125]
I don't know why, but all posts are being monitored , but one specific are not labeled.
Please see the attached picture to  understand. What can I do to discover which post is that?

![bug](https://user-images.githubusercontent.com/30931816/35805645-d4d963fa-0a63-11e8-824a-b589918dec0e.png)

**Comment by deconf** [comment]
Hi, that's probably because those pages don't have a "title" tag. You should check your theme and make sure all pages have a html title rag.
