### ISSUE TITLE
Caused error 500 (white screen)

### ISSUE THREAD

**Issue by Cycle-Fix** [deconf/Google-Analytics-Dashboard-for-WP#126]
![screen shot 2018-02-13 at 13 10 19](https://user-images.githubusercontent.com/36447655/36154930-df00b8b6-10ca-11e8-93a5-d813032865bd.png)
Also my Google Analytics plugin is corrupt & cannot be activated. I cannot seem to get round this. It will not delete or let me update it.
Thanks
Barry CYCLE-FIX

**Comment by deconf** [comment]
Hi,

Contact your hosting provider, it's a server side issue or uninstall it using the instructions here https://codex.wordpress.org/Managing_Plugins. You simply need to delete it using FTP and reinstall it.
