### ISSUE TITLE
Affiliate Regex Not Being Tracked

### ISSUE THREAD

**Issue by AdrianCGonzalez** [deconf/Google-Analytics-Dashboard-for-WP#127]
I am unable to see my events being tracked on google analytics website. I am not sure if it is the plugin I am using or there is something more I should be enabling.
I am using the plugin [Easy Affiliate Links](https://wordpress.org/plugins/easy-affiliate-links/) for reference.
Here are my settings:
```
ON | track downloads, mailto, telephone and outbound links
ON | track affiliate links
ON | track fragment identifiers, hashmarks (#) in URI links
ON | track form submit actions
ON | track page scrolling depth
Downloads Regex: |  zip|mp3*|mpe*g|pdf|docx*|pptx*|xlsx*|rar*
Affiliates Regex: |  /out/
Code Placement: | HTML Body
```

**Comment by deconf** [comment]
Hi,

Do your links match the pattern which is "/out/"? For details see https://deconf.com/tracking-google-analytics-dashboard-wordpress/ 

If not, you'll need to identify a common pattern that only matches the affiliate links.

Otherwise there's no way for the plugin to track them.
