### ISSUE TITLE
Wrong use of single_tag_title()

### ISSUE THREAD

**Issue by chesio** [deconf/Google-Analytics-Dashboard-for-WP#129]
Hi,

I noticed that category archive pages on one site using the plugin have category title printed in `<head>` section and I've been able to track this problem to this line: https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/master/front/tracking-tagmanager.php#L99

I guess you should call the [single_tag_title()](https://developer.wordpress.org/reference/functions/single_tag_title/) like: `single_tag_title('', false);` so the title is returned from the function instead of printed to output.

**Comment by deconf** [comment]
Hi and thanks for the report, it looks like the issue is only on the GTM component (https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/21c8bb82e39ee4cb78294fde419f834a474755f6/front/tracking-analytics.php#L58). We'll be fixed ASAP.
