### ISSUE TITLE
Enhancement suggestion:  Add Global Analytics Tracking code support

### ISSUE THREAD

**Issue by MarkNelwa** [deconf/Google-Analytics-Dashboard-for-WP#130]
Hello.  It would be great to see the new Google Global Analytics Tracking code to be supported with this plugin.

**Comment by deconf** [comment]
At the point where all features will be available with the new code it will.

**Comment by deconf** [comment]
There you go :), and thanks for the heads-up!

Global Site Tag is fully supported in v5.3.

**Comment by MarkNelwa** [comment]
Wow. I didn't expect a reply let alone a super quick update to the plugin to support the Google Global Tracking code.  Thank you very much.  You are awesome!!!
