### ISSUE TITLE
How to exclude your IP from Being Tracked

### ISSUE THREAD

**Issue by ToucheLady** [deconf/Google-Analytics-Dashboard-for-WP#131]
Hello, I have the Google Analytics Plug In and I can't seem to find where to change not tracking my IP. Does it have this feature?

**Comment by oodeveloper** [comment]
I think you can't from the panel; The are lots of ways you can do it: like directly from GA Dashboard or WP; I chose WP. So you can do it manually by blanking your code field from GADWP tracking code;
Then be always logged in so WP can detect you. Then in your footer.php do it like:
`<?php
$current_uid = get_current_user_id() ;
$exc_uid = 243; // your user id to be excluded in tracking entirely
if($current_uid != $exc_uid){
echo 'tracking code';
}`
* I thing GADWP can add this feature to the dashboard. I in fact came here to talk about this feature, then I saw this question.
GADWP it can be great if we can add Exclusion List base on users soon via the solution above
Thank you ;)

**Comment by deconf** [comment]
Actually this feature is available, see Google Analytics-> Tracking Code section. Furthermore excluding by IP is available on analytics.google.com throughout filters.
