### ISSUE TITLE
Dutch language .mo file missing

### ISSUE THREAD

**Issue by WillemJann** [deconf/Google-Analytics-Dashboard-for-WP#21]
The Dutch translation in version 4.7 of your plugin is currently not working, because for some reason the file ```ga-dash-nl_NL.po``` is missing. It was included in my pull request #17, but deleted in commit 0b4fc86bee3808f552641808fa01969543ce0c0d.

Any idea why the .mo file is not generated on your language files update?

**Comment by deconf** [comment]
Currently mo files are not generated for translations under 85%. For incomplete translations I had users complaining about having mixed messages and texts (part in locale language and part in english).

**Comment by WillemJann** [comment]
Ok, I just updated the translation to 100% (see PR #28).
