### ISSUE TITLE
tracking code

### ISSUE THREAD

**Issue by mythodeia** [deconf/Google-Analytics-Dashboard-for-WP#22]
Hello and thanks for this excellent library.
Quick question to which i did not find any answer in the forums.
My theme has added the tracking code for me.
Then i installed your plugin but disabled the tracking options in the basic settings as i do not want to have the tracking code twice injected in my pages. Even though the dashboard widget fetches data i do not see any data in the analytics column in the articles in the post admin area. 
So my question is this. Am i disabling the article tracking functionality by having the tracking code option disabled from your plugin? Since i had the tracking code already installed shouldn't i see data in the analytics column?
again thanks for your plugin and support

**Comment by deconf** [comment]
See: https://wordpress.org/support/topic/no-article-specific-data?replies=4#post-6756664

**Comment by mythodeia** [comment]
thanks for taking the time to respond :+1:  i will check on that asap

**Comment by mythodeia** [comment]
i checked the google analytics Behavior Flow->Site Content-> All Pages 
and for example i see this
```/design-lab-athens-2015/index.php```
i go to the wp posts admin and the stats for this is zero. 
the full url for that article is 
```
http://www.nexusmedia.gr/design-lab-athens-2015/index.php
```
can you explain how / where should i use the gadwp_backenditem_uri?
where do i insert it?

**Comment by deconf** [comment]
See this example:

https://deconf.com/ask/question/post-icon-for-analytics-always-show-cero/

**Comment by mythodeia** [comment]
problem solved. for anyone else that might read this inside the google analytics view settings for my website there was a default page filled with index.php.
removed that and i started seeing results.

thanks for your support on this matter. keep up the good work
