### ISSUE TITLE
Analytics for Membership site

### ISSUE THREAD

**Issue by JaroSK** [deconf/Google-Analytics-Dashboard-for-WP#23]
Hi, I'm building a membership site. I have this plugin already for a while and I see activity there but it's bit inaccurate. It tell how many user been to site but it doesn't distinguish between user just visited randomly site and users who's logged in, or are logged in right now. Any chance for implementing this? Thank you!

Regards,
Jaro

**Comment by deconf** [comment]
The plugin has the capability to track guests vs registered, please read the tracking documentation.

There are no reports for those custom definitions, but you can check the reports in your Google Analytics account.
