### ISSUE TITLE
Bounce rate 100% number formatting in graph

### ISSUE THREAD

**Issue by sdellenb** [deconf/Google-Analytics-Dashboard-for-WP#27]
__Versions__
* WordPress 4.2.2
* Google Analytics Dashboard for WP 4.7.3

__Steps to reproduce__ (well, can't really control access to the site)
1. In the Dashboard Widget, set timeframe 'Today' or 'Yesterday' and pick 'Bounce Rate' stats.
2. Hover over the data points

__Result__
* When during one hour, there have only been one-time requests (100% bounce rate), the number is formatted as __1,00,00%__)

__Expected Result__
* Number is formatted as __100%__.
It is correct numbers below 100, like 84,21%, 50,00% and 0%

_It's only a very minor display issue, but I thought I'd report it anyways..._ :smiley:

**Comment by deconf** [comment]
Thanks for the report, I'll have a look.
