### ISSUE TITLE
Dashboard not displaying Settings

### ISSUE THREAD

**Issue by ZaraAltair** [deconf/Google-Analytics-Dashboard-for-WP#30]
![dashboard lack settings

Hi 
I am unable to access Settings after download and activate.
Choices are Deactivate and Edit.

**Comment by deconf** [comment]
Hi,

Give more details like WP version, multisite or single install, default language, a screenshot and anything else that may be helpful

**Comment by ZaraAltair** [comment]
Hi Alin,
Version 4.2.2
Single Install
Default language English
gave you a screenshot already but see attached
All I know. Installed today.
Thanks.
Zara


  [image: photo]
*Zara Altair*
Web Presence for Business Growth, Actation Now!
 p:503 468 7008 | m:5034687008 | e:zara@actationnow.com | w:
http://actationnow.com | a:Google Me goo.gl/aN4SoG
    Get a signature like this:
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>


*Connectivity for business growth.*

**Comment by deconf** [comment]
Thank you!

**Comment by ZaraAltair** [comment]
Hi Alin,
The settings appeared over on the WP dashboard side bar.

I know this sounds like a crazy question, but where to I see the results?

Zara


  [image: photo]
*Zara Altair*
Web Presence for Business Growth, Actation Now!
 p:503 468 7008 | m:5034687008 | e:zara@actationnow.com | w:
http://actationnow.com | a:Google Me goo.gl/aN4SoG
    Get a signature like this:
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>


*Connectivity for business growth.*
