### ISSUE TITLE
Formatting numbers and dates

### ISSUE THREAD

**Issue by IvanRF** [deconf/Google-Analytics-Dashboard-for-WP#34]
First of all, great plugin!!
Is it possible to add thousands separators to the numbers in the main dashboard widget? (like in Google Analytics reports)
Also, decimal separators should be locale-aware. That is, I'm seeing 22**.**34% in Spanish, and it should be 22**,**34%. Same thing applies if you add thousands separators :+1:

**Comment by IvanRF** [comment]
I just found that dates in graphs also need formatting to be locale-aware.
If I choose "One Year" in the main dashboard widget I see "July, 2015-07" which is only in English.
If I choose "Last 30 days", I see "Lunes, 2015-07-27" which has the correct day in Spanish, but the date in numbers uses English notation.

**Comment by deconf** [comment]
It will a little complicated to localize the numbers there, but the month name is an easy fix.

**Comment by IvanRF** [comment]
I just added localization for numbers. I used javascript `toLocaleString()` along with php `get_bloginfo( 'language' )`.
I only changed the widget from the main dashboard. If you like this option, you should also change /front/js/item-reports.js and /admin/js/item-reports.js

**Comment by deconf** [comment]
Please do, looks fine.

**Comment by deconf** [comment]
We just need to make sure it's supported by Google Charts (that's why I said it may be "a little complicated") :).

**Comment by IvanRF** [comment]
No, in-chart values are fine. I just tried a previous version (4.8.1.2) and it shows
> Miércoles, 2015-07-08
> Bounce Rate:23,29%

As you can see, the percent number is already formatted by Google. In this case, the date needs formatting.

Do you want me to change the item-reports.js? Where is this file used? (to test it)

**Comment by IvanRF** [comment]
In-chart values were right in Firefox, but wrong in Chrome.
So, I read about and found this: [Loading Charts using a specific locale](https://developers.google.com/chart/interactive/docs/library_loading_enhancements#loadwithlocale)
> By default, the Google Chart libraries are loaded with the locale specified by the browser

I added the code to load the library with WordPress language. Again, it's up to you if you want to use this code for the other `google.load("visualization",...`

**Comment by deconf** [comment]
item-reports.js is used for frontend reports and per page or post reports on backend, for reports like: https://pull-deconf1.netdna-ssl.com/wp-content/uploads/2015/06/ga-posts-reports.png

**Comment by IvanRF** [comment]
I made the specific changes to localize item-reports.js too and tested them both in Firefox and Chrome.

**Comment by IvanRF** [comment]
I updated the code related to dates. I used [date_i18n](https://codex.wordpress.org/Function_Reference/date_i18n).
One Year option will show 'month, year'.
For days I had to use this format: `'l, ' . __( 'F j, Y' )`. The first part will show the localized day and the second part localizes the format first and then the date. It was the only way to localize everything, since using `'l, F j, Y'` or `__( 'l, F j, Y' )` breaks localization.
After this, I think you can close this issue.

**Comment by deconf** [comment]
Thank you, I've switched to number_format_i18n() because it's more reliable since there are some support issues in Safari for toLocaleString()

**Comment by IvanRF** [comment]
Much better! I used a javascript solution since I didn't know where in the code could be applied a php solution. Glad to help with i18n, waiting for the WP plugin update now 😊

**Comment by deconf** [comment]
It was scheduled for today, but during the beta testing the Safari issue and some other minor issues surfaced and I want to have it fully tested again.

Since there are lots of changes (thank you, again!) I won't push it as an automatic update, I'll probably have to release it as a separate 4.8.2.
