### ISSUE TITLE
Invalid response, more details in JavaScript Console (F12).

### ISSUE THREAD

**Issue by flowl** [deconf/Google-Analytics-Dashboard-for-WP#4]
Since the last update (yesterday),the dashboard shows this error:
Invalid response, more details in JavaScript Console (F12).
But there are no errors in the console.
The graph is loading veeeerrryyy long (about 2-3 minutes), and it often does not finish loading.

**Comment by deconf** [comment]
Are you sure you're looking in the right place? In Chrome, Firefox or IE press F12 and select the Console tab.

If blog.flowl.info is your website, check this out:

blog.flowl.info/wp-admin/admin-ajax.php

Is not ok to have such an certificate error while accessing that file!

The Google API response varies between 0.7 and 1.3 seconds (most of the time), anything above that it's usually a server configuration issue.

**Comment by flowl** [comment]
Sorry, I cannot effort a valid certificate, too expensive.
Response time is 150ms. The Graph is not shown initially, might be a bug in Firefox OSX. After I scroll down and up, the graph is displayed.
But still there is "Invalid Response..." error with a red bar left to it.
The responses are (Users in the past 7 Days):

action: gadashadmin_get_widgetreports

[["Date","Users"],["Monday, 2015-02-02",4809],["Tuesday, 2015-02-03",5654],["Wednesday, 2015-02-04",6446,["Thursday, 2015-02-05",6998],["Friday, 2015-02-06",5720],["Saturday, 2015-02-07",5015],["Sunday, 2015-02-08",4449]]


gadashadmin_get_widgetreports

["44812","36167","57398","85.71428571428571","23945","1.2790178571428572"]
["448","361","573","85.71428571428571","239","1.2790178571428572"]

**Comment by deconf** [comment]
Then don't force https there, you should remove https for that file.

**Comment by flowl** [comment]
This is the most stupid advice ever. Disable https lol I'd rather disable your plugin.
As I don't have any Ajax (or requests to admin-ajax.php), I can safely use a local cert on it.
Btw I tried without https, still the same bug.

**Comment by flowl** [comment]
Haha there are other ppl with this problem.
https://wordpress.org/support/topic/invalid-response-more-details-in-javascript-console-f12
Why you deny to admit your software has a bug?
Why instead you hatin on my certificate?
Don't be stupid man.

**Comment by deconf** [comment]
For support use https://deconf.com/ask/, thank you.
