### ISSUE TITLE
Translations lost

### ISSUE THREAD

**Issue by IvanRF** [deconf/Google-Analytics-Dashboard-for-WP#41]
With the latest update (4.8.2.1) I have lost my Spanish translations.

Also, if you want to add me to the new `GADWP Translation Editors` section, this is my profile

`+Spanish - [IvanRF](https://profiles.wordpress.org/ivanrf/)`

**Comment by IvanRF** [comment]
I just look in the plugin folder and differs with GitHub. The `languages` folder **has wrong files**. The name is wrong "wp-plugins-google-analytics-dashboard-for-wp-dev-" and there are many languages missing.

**Comment by deconf** [comment]
Hi, the translations are not lost! I'm just switching to translate.wordpress.org. See: https://translate.wordpress.org/projects/wp-plugins/google-analytics-dashboard-for-wp

From 4.8.3 all translation files will be delivered from translate.wordpress.org, as language packages. The only requirement is that you must have the translation at 100% to receive the language pack.

These being said, I'll head on and add make a request to #es for TE rights.

**Comment by IvanRF** [comment]
I saw that link but I'm not familiar with translate.wordpress.org. Is this a new system for translations? I saw translation update notifications for other plugins in wordpress admin, is related to this?

Does that mean that if a language is not at 100%, partial translations will not be used?

**Comment by deconf** [comment]
Yes, right now only if a translation is at 100% is delivered as a language pack. Please note that Development (trunk) will allow you to have instant access to the next set of strings, Stable (latest release) is for current release and the other two projects is for plugin description only (on ES is for the contents of this page: https://es.wordpress.org/plugins/google-analytics-dashboard-for-wp/).

Shortly, if the Stable (latest release) is at 100% the lang pack will be available for update (no matter the status of the rest of the projects). If the Stable Readme (latest release) is at 100%, the plugin description and all tabs will also get translated on https://es.wordpress.org/plugins/google-analytics-dashboard-for-wp/.

**Comment by IvanRF** [comment]
As I saw in the comments, I need to wait for an invitation, right? After that, do I need to translate the strings from Development (trunk) or Stable (latest release)?

**Comment by deconf** [comment]
Yes, and after confirming it, comment there, so the GTE can add you to my project. Translate the stable (is actually only one string). If you like you can continue with the readme stable too. After finishing them you'll notice that the exact match strings will also get translated automatically on trunk. After that point make sure the trunks are at 100% all the time and when the trunk becomes a stable (when I make a new release) the language packs will be available instantly.

**Comment by IvanRF** [comment]
I just accepted the invitation https://es.wordpress.org/newbloguser/...

**Comment by deconf** [comment]
Is quite straight-forward process and if you love the third party translation tool you may be using, you can export the PO files, translate there and re-import them as Translation Editor.

**Comment by IvanRF** [comment]
Now Spanish is at 100%. Regarding the trunk, do you mean this folder?
http://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/trunk/languages/

Shouldn't es_ES be there then?

**Comment by deconf** [comment]
No, by trunk  I'm referring to these projects: https://translate.wordpress.org/projects/wp-plugins/google-analytics-dashboard-for-wp

As mentioned above, the package updates will be fully functional from GADWP version 4.8.3!

**Comment by IvanRF** [comment]
One last question, Yoast SEO plugin saves the translations on `/wp-content/languages/plugins/` and they appear as Update notifications when there are changes only on translations. Is this what you are adding on version 4.8.3? or they use a different approach?

**Comment by deconf** [comment]
Here are more details about this feature: https://deconf.com/moving-translations-to-wordpress-org/

**Comment by IvanRF** [comment]
Nice! It was what I thought then.
Where can I find documentation on how to implement this on a plugin?

**Comment by deconf** [comment]
https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

**Comment by IvanRF** [comment]
Thanks!

**Comment by deconf** [comment]
At this moment with 4.8.3 you should have an update and Spanish translation available

**Comment by IvanRF** [comment]
Yes, Spanish is translated now :)

**Comment by deconf** [comment]
@IvanRF can you please contact me, I need your e-mail address to add you on my alert list for translators. Thank You!
