### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OsteoFan** [deconf/Google-Analytics-Dashboard-for-WP#43]
Hello,

For some reason i got this error. Do you know what i can do?

Greetings,
Paul

Error Details

Error Details: 
2015-10-30 16:43:38: exception 'Google_Auth_Exception' with message 'Error fetching OAuth2 access token, message: 'invalid_grant'' in /mnt/webp/a2/26/53398226/htdocs/WordPress_01/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Auth/OAuth2.php:126
Stack trace:
#0 /mnt/webp/a2/26/53398226/htdocs/WordPress_01/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Client.php(133): Google_Auth_OAuth2->authenticate('Last Error: 201...')
#1 /mnt/webp/a2/26/53398226/htdocs/WordPress_01/wp-content/plugins/google-analytics-dashboard-for-wp/admin/settings.php(722): Google_Client->authenticate('Last Error: 201...')
#2 [internal function]: GADWP_Settings::general_settings('')
#3 /mnt/webp/a2/26/53398226/htdocs/WordPress_01/wp-includes/plugin.php(503): call_user_func_array(Array, Array)
#4 /mnt/webp/a2/26/53398226/htdocs/WordPress_01/wp-admin/admin.php(236): do_action('toplevel_page_g...')
#5 {main}
ResponseHttpCode:400

**Comment by deconf** [comment]
For support check the support forum: https://wordpress.org/support/plugin/google-analytics-dashboard-for-wp
