### ISSUE TITLE
inaccurate stats

### ISSUE THREAD

**Issue by portkd** [deconf/Google-Analytics-Dashboard-for-WP#44]
Two days ago, the Google Analytics Dashboard started displaying the wrong stats. It showed I had 12 people on my website the whole day, when that number was probably 250. The next day I confirmed with the IT people who can access the Google Analytics account that I had 75 people on my site when the dashboard was registering 2. 

On their end, they see the correct stats. On my end, they are completely wrong. How do I fix this?

I tried deactivating and reactivating. If I clear the cache, will I lose my previous stats? I am able to see back the whole year and see the progress I've made. I'd prefer that not disappear. 

My website: http://portwashington-news.com/
Thank you.

**Comment by deconf** [comment]
For support, always use: https://wordpress.org/support/plugin/google-analytics-dashboard-for-wp

To quickly answer your questions:
 
1. Your tracking code is inserted multiple times in a page (three times to be more accurate), you should fix that as soon as possible, see: https://deconf.com/check-google-analytics-tracking-works/

2. You can find your answer about losing previous stats in plugin's FAQ page: https://deconf.com/faq-about-google-analytics-dashboard-for-wordpress/
