### ISSUE TITLE
Option to disable plugin update notification

### ISSUE THREAD

**Issue by newdesignideas** [deconf/Google-Analytics-Dashboard-for-WP#46]
Every time the plugin is updated an annoying notification is displayed to all users simply notifiying that the plugin is updated - most of the users have no need to see that (even most of the admins). As the plugin is updated frequently - it does get annoying after a time for the more experienced user and the less experienced are simply confused by it.

**Comment by deconf** [comment]
I know, but at the same time users want to know when an automatic update occurred.

As an improvement, on next version the notification will only be available to the admins (see the latest development version).

**Comment by deconf** [comment]
Right now the notice is only displayed on the Dashboard screen and only to Administrators
