### ISSUE TITLE
Broken view widget in console page

### ISSUE THREAD

**Issue by hotpaganini** [deconf/Google-Analytics-Dashboard-for-WP#48]
WP 4,4 GooAnl  4.9.0.1, Chrome, FF - last stable bilds
In Console page, widget looking very strange. Main graph appears only with mouse hover... so, I cant control form settiings. Reinstall, reactivate, of course, have no effect.
Shot: http://c2n.me/3rvZHgz.png

**Comment by deconf** [comment]
Hi, this looks like a support question. Try to disable all plugins and switch to a default theme. It maybe a theme/plugin conflict. For further support please use: https://wordpress.org/support/plugin/google-analytics-dashboard-for-wp
