### ISSUE TITLE
Not showing referrals or country etc.

### ISSUE THREAD

**Issue by meganb2** [deconf/Google-Analytics-Dashboard-for-WP#5]
Hi, i use google analytics plugin. It still shows number of users by time etc. (the top portion of the dashboard). but one day the bottom portion of the dashboard disappeared. The part where you can see the users by country / referrals etc. I didn't update anything and it disappeared about a month ago. No errors/ bugs are reported. Help!

**Comment by deconf** [comment]
This is not a bug, read the announcement: https://deconf.com/new-features-google-analytics-dashboard-4-4-wordpress/

**Comment by meganb2** [comment]
thank you. clearly i'm not a computer wiz & i appreciate your help!
