### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by codingyourlife** [deconf/Google-Analytics-Dashboard-for-WP#53]
Everytime I opened wp-admin after a longer time it took like 1 minute where whole site was down to show the dashboard. But now not even that. I tried to reauthenticate but after pasting and applying the new code from google it get's stuck on an empty content page of wp backend.

Here the error:
Last Error: 2016-01-13 20:47:49: exception 'Google_IO_Exception' with message 'Failed to connect to 2a00:1450:4005:803::200d: Network is unreachable' in /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/IO/Curl.php:86
Stack trace:
#0 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/IO/Abstract.php(135): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Auth/OAuth2.php(113): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Client.php(133): Google_Auth_OAuth2->authenticate('[CENSORED]')
#3 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/admin/settings.php(739): Google_Client->authenticate('[CENSORED]')
#4 [internal function]: GADWP_Settings::general_settings('')
#5 /home/.sites/97/site1310/web/sites/blog/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
#6 /home/.sites/97/site1310/web/sites/blog/wp-admin/admin.php(236): do_action('toplevel_page_g...')
#7 {main}

**Comment by deconf** [comment]
Hi,

This not a bug, it's a server/network configuration issue, for details see plugin's FAQ: https://deconf.com/faq-about-google-analytics-dashboard-for-wordpress/

**Comment by codingyourlife** [comment]
Do you know is this a Google Bug or a problem of my hoster?

**Comment by deconf** [comment]
As I said above, see the FAQ page and <strong>Google_IO_Exception and Failed to connect errors</strong> section, it's all there.

**Comment by codingyourlife** [comment]
Just to finish this up. This seems to have worked putting in the wp-config.php:
define('GADWP_IP_VERSION', 1);
define('CURLOPT_IPRESOLVE', 113);
define('CURL_IPRESOLVE_V4', 1);
