### ISSUE TITLE
Analytics in individual post is not working

### ISSUE THREAD

**Issue by benromero** [deconf/Google-Analytics-Dashboard-for-WP#56]
Great plugin!

After installing the latest update, the plugin is not showing the analytics for individual posts correctly when clicking in the analytics icon for every post.

<img width="1262" alt="captura de pantalla 2016-02-18 a las 18 43 36" src="https://cloud.githubusercontent.com/assets/3774766/13154169/8e318f06-d66f-11e5-998c-21ae8c0299ae.png">

**Comment by adeguzm1** [comment]
@benromero I'm getting the same, did you find a solution?
