### ISSUE TITLE
Cannot Auto-Update with Jetpack

### ISSUE THREAD

**Issue by joedoq** [deconf/Google-Analytics-Dashboard-for-WP#58]
I tried enabling auto-update with Jetpack but even after uninstalling I still get this error: 
"This plugin is not in the WordPress.org plugin repository, so we can't autoupdate it."
It would be great if the plugin could be auto-updated. 

Thanks! And great plugin! 
Keep up the good work!

**Comment by deconf** [comment]
Are you sure you have installed it from WordPress official pligin directory https://wordpress.org/plugins/google-analytics-dashboard-for-wp/. Also make sure the plugin slug is correct.
