### ISSUE TITLE
Unknown page in overview

### ISSUE THREAD

**Issue by Heribert2** [deconf/Google-Analytics-Dashboard-for-WP#60]
Hi,

In the overview on the dashboard I have a page: **forum.topic75417805.6hopping.com** which doesn't belong to my site at all.

I have search the directories and the website and I can't find any reference to  this or part of it.
I also can't see it at Google Analytics site

Domain is www.northhartismerebenefice.org.uk

I will try to delete all files of the plug in and reinstall it to see if it comes back...

Heribert

**Comment by deconf** [comment]
Hi,

For support use the forums. By the way, your question was already answered here https://wordpress.org/support/topic/do-your-plugin-spam-on-spacebarnotwork?replies=3 and there's a tutorial on my website about steps to take to avoid spam.

**Comment by Heribert2** [comment]
Thank you Alin,

 

Sorry for the inconvenience…

 

Heribert
