### ISSUE TITLE
not working with woocommerce analytics pro may be also 

### ISSUE THREAD

**Issue by Tobias-Conrad** [deconf/Google-Analytics-Dashboard-for-WP#61]
401 error because both plugins are connected to GA.
This error occurs after some visits ans minutes.
https://de.wordpress.org/plugins/woocommerce-google-analytics-integration/

**Comment by deconf** [comment]
Hi,

401 error is too generic. Please provide the error log details from Error & Debug screen of GADWP.

**Comment by Tobias-Conrad** [comment]
please test and make compatible. i deleted plugin for now.
www.woothemes.com/products/woocommerce-google-analytics-pro

**Comment by deconf** [comment]
As I already said on WP forums, the code of the plugin is not public, being a premium plugin (the second link you've posted). Since you have a premium plugin, support for that plugin, and my code is public, you should ask them for a fix.
