### ISSUE TITLE
Feature Request / Idea: User ID tracking

### ISSUE THREAD

**Issue by bhalpern** [deconf/Google-Analytics-Dashboard-for-WP#64]
Hi there--

The (relatively) new User Explorer feature of Google Analytics makes tracking at the individual visitor level much more fluid. To help evaluate the logged in user experience, it'd be great to see this plugin assign unique identifiers to WordPress users and possibly even allow viewing analytics on each user's page in the backend. I can see two valuable options for admins to choose from:
- Assign identifiers only to users only when logged in, or
- Assign identifiers to users on login, and allow the cookie to persist on logout (but be overwritten if another user logs in).

AND
- Set an identifier cookie for non-logged in / non-identifiable users (yes or no)

Of course, an important aspect of this would be the ability to align the unique identifier with meaningful user information.

https://support.google.com/analytics/answer/3123662
https://support.google.com/analytics/answer/3123663

Just an idea!

**Comment by deconf** [comment]
See https://gist.github.com/deconf/23cbc2b169c8334edef2ed4d54de3cd6.
