### ISSUE TITLE
Google OAuth - invalid_request - missing client_id

### ISSUE THREAD

**Issue by thomasfw** [deconf/Google-Analytics-Dashboard-for-WP#65]
When clicking the 'Get Access Code' link to retrieve my access code, Google displays the following page..

```
400. That’s an error.

Error: invalid_request

Missing required parameter: client_id
```

Additional request details (from the same page)..

```
access_type=offline
approval_prompt=auto
scope=https://www.googleapis.com/auth/analytics.readonly
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=
```

**Comment by deconf** [comment]
That's a configuration error, check the documentation page and follow the introductory video.
