### ISSUE TITLE
Hook for preventing tracking code output

### ISSUE THREAD

**Issue by thomasfw** [deconf/Google-Analytics-Dashboard-for-WP#66]
Is there a hook/filter I can use to prevent the final output of the tracking code.

My site is running in multiple environments, so I wish to disable the tracking code on all but the production site based on my ENV config.

I've looked through the code, and have also looked for some kind of developer documentation but have so far been unsuccessful.

Thanks

**Comment by deconf** [comment]
See https://gist.github.com/deconf/ad5fa23ec3de4eac517c
