### ISSUE TITLE
Cross-domain tracking

### ISSUE THREAD

**Issue by alexey-pelykh** [deconf/Google-Analytics-Dashboard-for-WP#67]
https://support.google.com/analytics/answer/1034342?hl=en#GA says that each domain should not include itself in linker:autoLink
Probably code here
https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/master/front/tracking/code-universal.php#L53
needs to be adjusted a bit to exclude currently served URL

Please confirm my understanding and I'd be happy to provide a pull-request.

**Comment by alexey-pelykh** [comment]
More information: I have multiple domains hosted on a single instance using qTranslate-X

**Comment by alexey-pelykh** [comment]
Something like this:
`
diff --git a/wp-content/plugins/google-analytics-dashboard-for-wp/front/tracking/code-universal.php b/wp-content/plugins/google-analytics-dashboard-for-wp/front/tracking/code-universal.php
index deab0ca..ea93a51 100644
--- a/wp-content/plugins/google-analytics-dashboard-for-wp/front/tracking/code-universal.php
+++ b/wp-content/plugins/google-analytics-dashboard-for-wp/front/tracking/code-universal.php
@@ -52,6 +52,7 @@ if ( ! empty( $optionsArray ) ) {
 <?php
 	$crossdomain_list = explode( ',', $this->gadwp->config->options['ga_crossdomain_list'] );
 	$crossdomain_list = array_map( 'trim', $crossdomain_list );
+	$crossdomain_list = array_diff( $crossdomain_list, [ parse_url( get_home_url(), PHP_URL_HOST ) ] );
 	$crossdomain_list = strip_tags( implode( "','", $crossdomain_list ) );
 	?>
   ga('linker:autoLink', ['<?php echo ($crossdomain_list)?>'] );
`

**Comment by deconf** [comment]
Hi,

The crossdomain_list is created based on user input. The user shouldn't enter its current domain in the first place. While it could be an additional validation I would prefer to leverage it on user side (input). Relying on `parse_url( get_home_url(), PHP_URL_HOST ) `]`` can result in some unwanted side effects, altering the user input, which isn't desirable.

**Comment by deconf** [comment]
For your particular case I would use a custom function or even a little custom plugin to alter the `$this->gadwp->config->options['ga_crossdomain_list']` property before the tracking code output.

**Comment by alexey-pelykh** [comment]
Hey,

Yes, but when using GADWP + qTranslate-X with a multi-domain setup (domain.com + domain.de + domain.se) to properly track visitors I need to setup domain.de + domain.se on domain.com, domain.de + domain.com on domain.se and so on. I would say this is not a super rare usecase. Maybe I should add a checkbox somewhere?
