### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by blitz999** [deconf/Google-Analytics-Dashboard-for-WP#68]
Hi, great plugin idea. Just setting up and getting this when going for an access code:

400. That’s an error.

Error: invalid_request

Missing required parameter: client_id

Learn more

Request Details
access_type=offline
approval_prompt=auto
scope=https://www.googleapis.com/auth/analytics.readonly
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=
That’s all we know.

**Comment by deconf** [comment]
Hi, you're receiving that error because you haven't configured properly the plugin. For details check-out the documentation page.

**Comment by blitz999** [comment]
The plugin defaults 'use own credentials' as ticked. This is what causes the error when you try to authorise. I might suggest fixing this by defaulting to unticked, so this error message does not appear.

Thanks for getting back to me otherwise.

**Comment by deconf** [comment]
By default the option is unchecked.

**Comment by blitz999** [comment]
Don't worry, I've found a different plugin that works.
