### ISSUE TITLE
Support segments

### ISSUE THREAD

**Issue by vinnie2k** [deconf/Google-Analytics-Dashboard-for-WP#70]
Supporting segments would help the dashboard show "real data" instead of unfiltered unsegmented data.

**Comment by deconf** [comment]
Can you develop a little the idea, maybe by giving some examples?

**Comment by vinnie2k** [comment]
Add a drop-down menu to the dashboard widget; the content of that menu are the segments defined by users in their Google Analytics profiles. These segments filter the data in some meaningful manner, for example to take out hits from bots or from users themselves.
