### ISSUE TITLE
Property Views - Multisite

### ISSUE THREAD

**Issue by adsric** [deconf/Google-Analytics-Dashboard-for-WP#72]
I believe the Property Views in the network admin are not being updated with a selected state.

**Comment by deconf** [comment]
Yes, that's right, it's a PHP7 issue which is fixed in [4.9.4](https://github.com/deconf/Google-Analytics-Dashboard-for-WP/commit/5a4ce52ccb61a998bd0ee6c6ee11253eb1b51c06)
