### ISSUE TITLE
Feature Request: Restricted stats based on custom dimensions

### ISSUE THREAD

**Issue by WillJW** [deconf/Google-Analytics-Dashboard-for-WP#73]
In my use case, I have a multi-site network with a single tracking code. Each site in the network sets a couple of custom dimensions (site ID, site name) so we can separate this data in our Google Analytics dashboard, which works great.

What I'd like to be able to do is show graphs in the WordPress backend for each of the sites, using only data for that specific site, based on the 'site ID' custom dimension.

Essentially, I don't want editors for one site seeing the whole network's traffic stats.

**Comment by deconf** [comment]
GADWP, is designed to separate this data using Properties and Views. Such an implementation will completely change the default behavior. If it will be to implement such a feature, will probably be an independent add-on for GADWP.
