### ISSUE TITLE
Support for HTTPS URLs

### ISSUE THREAD

**Issue by AlecRust** [deconf/Google-Analytics-Dashboard-for-WP#75]
If your Google Analytics property is set to use HTTPS as the default URL e.g.

![screenshot](https://i.imgur.com/7stYyXt.png)

This isn't reflected in the "General Settings" section of the plugin settings:

![screenshot](https://i.imgur.com/dthLTlm.png)

Perhaps the protocol could be picked up by the plugin to prevent potential confusion here?

**Comment by deconf** [comment]
Hi,

The protocol is always retrieved from your Google Analytics account. Please make sure is properly updated in your Property and Views settings. After updating it, you'll need to clear the authorization and re-authorize the plugin, to force a complete refresh of your Properties and Views data.
