### ISSUE TITLE
Weekly total of users visiting is different from daily totals added up

### ISSUE THREAD

**Issue by pchees** [deconf/Google-Analytics-Dashboard-for-WP#80]
Hi

When I select the last 7 days data on the dashboard there is a weekly total presented e.g. 90 users who have visited my sites. However, when I add up each individual day over the 7 days I get a total of 115 users.

Why is there a discrepancy?

![image](https://cloud.githubusercontent.com/assets/24203951/20646794/6d5c5b60-b49c-11e6-9406-e924d9017e2e.png)

**Comment by deconf** [comment]
Hi,

You're doing it wrong, you can't sum users by day and compare the result with an interval, because for example an user visiting your site in two different days gets counted twice, which is incorrect.
