### ISSUE TITLE
Optimizepress Theme Conflict

### ISSUE THREAD

**Issue by cristianciuberea** [deconf/Google-Analytics-Dashboard-for-WP#81]
Hi,

When Optimizepress Theme is active, the dashboard widget won't work http://prntscr.com/dd6x3j

I have this problem on several blogs.

**Comment by deconf** [comment]
Hi,

See the FAQ page https://deconf.com/faq-about-google-analytics-dashboard-for-wordpress/.

Most probably your theme is generating a JavaScript error in the dashboard blocking all other JavaScript code that follows.

**Comment by cristianciuberea** [comment]
Hi, the last update fix this conflict. Thanks
