### ISSUE TITLE
Feature: opt-out cookie/script

### ISSUE THREAD

**Issue by kulmann** [deconf/Google-Analytics-Dashboard-for-WP#82]
In Germany we have the following requirements for the privacy policy of a website:
1) a link to the opt out plugin for google analytics and
2) (new) a link to set up an opt out cookie for the website (since mobile devices can't have a browser plugin for the opt out)

For 2) some code would have to be added to your plugin. It would be great if you could be so kind. :-) You can find the js snippet if you follow this link: [Webgilde.com](https://webgilde.com/en/analytics-opt-out/) and scroll to "Opt-Out Script". Or here:

```javascript
<script>
// Set to the same value as the web property used on the site
var gaProperty = 'UA-XXXX-Y';

// Disable tracking if the opt-out cookie exists.
var disableStr = 'ga-disable-' + gaProperty;
if (document.cookie.indexOf(disableStr + '=true') > -1) {
  window[disableStr] = true;
}

// Opt-out function
function gaOptout() {
  document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window[disableStr] = true;
}
</script>
```

The cookie then can be triggered with a link to javascript:gaOptout().

Thanks in advance!

**Comment by deconf** [comment]
Hi,

We can't implement a feature for each country requirements. It's virtual impossible to do so, via UI, without cluttering the plugin with lots of options.

Instead, the plugin provides ways to programmatically disable features on-the-fly using filters and actions based on user's choices. For example, if you need to disable tracking based on a user preference stored in a cookie, in your functions.php file, you'll check the cookie and if the conditions are met you can simply unhook the tracking code, see https://gist.github.com/deconf/ad5fa23ec3de4eac517c.

**Comment by kulmann** [comment]
Hi,

thanks for your reply, I will try that.

I think that the possibility to disable GA-tracking with a cookie is not only relevant for germany but for others countries as well. It's just that germany seems to be very strict about that. I hope you reconsider the feature request if further countries are overreacting about this stuff, too. ;-)

However, thanks again for your help!

**Comment by deconf** [comment]
I'm aware of it since I'm also from an EU country and facing similar "chalanges". But, as we know, the EU directive is applied on every country so differently that the best option I see right now is meeting the requirements through code rather than having lots of options that won't make sense for some and be very useful for others. 

Thank you for the feedback, is very appreciated.

**Comment by deconf** [comment]
Related #89. Things are much simpler in analytics.js. The optout script will just need to set a window property to disable tracking.
