### ISSUE TITLE
Your plugin window size is more than specified space in the wordpress dashboard ! 

### ISSUE THREAD

**Issue by arashtarh** [deconf/Google-Analytics-Dashboard-for-WP#88]
I have used Google Analytics Dashboard successfully on my http://www.tarhekhas.com ( wordpress 4.2.11 and your plugin version 4.9.3.1) ; but on the other website ( http://www.kojaberim.info ) which I have installed the latest version of this plugin on it ,  The plugin needs more space in the wordpress dashboard to show the analytics information correctly ! 
i don't know this problem relates to the version of your plugin or not but i have installed just the latest one (4.9.5)  and my wordpress version is 4.5.5 .
![analytics error](https://cloud.githubusercontent.com/assets/25330654/22271885/37980cb6-e2ac-11e6-8871-33fc61326823.jpg)

**Comment by deconf** [comment]
Hi,

If you still have the issue can you tell me the WordPress Language you're using? It could be a localization issue.
