### ISSUE TITLE
Opt-Out Function

### ISSUE THREAD

**Issue by felixhirschfeld** [deconf/Google-Analytics-Dashboard-for-WP#89]
Would you like to implement the popular opt-out function? :) Then theres no need for extra pplugin or coding

<script>
	var gaProperty = 'UA-XXX-X';
	var disableStr = 'ga-disable-' + gaProperty;
	if (document.cookie.indexOf(disableStr + '=true') > -1) {
		window[disableStr] = true;
	}
	function gaOptout() {
		document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
		window[disableStr] = true;
	}
	</script>

**Comment by deconf** [comment]
Hi,

The above function is for ga.js, which is deprecated. For analytics.js there is a simpler method:
`window['ga-disable-UA-XXXXX-Y'] = true;`
For details see https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out.
So bassicaly, the optout script will just need to define that line and set it to true to disable the tracking.
