### ISSUE TITLE
A few thoughts

### ISSUE THREAD

**Issue by paaljoachim** [deconf/Google-Analytics-Dashboard-for-WP#9]
Very nice plugin btw. I use it a lot!

I have a bunch of suggestions/adjustments that can be made.

General Settings.
Hide all other domains. Make the button a bit smaller. It takes so much space. Do also turn off vertical align for .button-secondary. What about just making it into a text link.
Just the text below the drop down. A simple text link could be: Hide other domains. 
Something like this:

![google-analytics-dashboard-wp-plugin](https://cloud.githubusercontent.com/assets/5323259/6770512/04fd21a4-d0c2-11e4-8184-62da45454939.jpg)

Instead of this:

![screen shot 2015-03-22 at 18 28 50](https://cloud.githubusercontent.com/assets/5323259/6770517/10fbe30a-d0c2-11e4-9674-a6b4bb541f40.png)

Backend Settings.
The title of the page says General Settings. Please change this to Backend Settings as that is the name of the section.
On/Off disable Switch Profile/View functionality. It would be better to have the button say enable switch profile/view functionality. Having someone turn the button on to see additional stats for domains one have in the selected Google Analytics account.

Here is a suggestion for reworking the section:
![google-analytics-dashboard-wp-backend-settings](https://cloud.githubusercontent.com/assets/5323259/6770811/80e9c2d6-d0cc-11e4-9fa9-6420480634e6.jpg)

- I added an exclude tracking and turned on Administrator. As it is important not to track the administrator it is good to have a checkmark in the box.
- I changed disable to enable.

It is important to get the important things into the Backend settings section. Less important features moved to another place.

Frontend Settings.
Do also change the title from General Settings to Frontend Settings.
Do also include a link to your site for info about the frontend settings.

Tracking Code
Custom Definitions. It would be nice with a text link to your site (or google analytics)  explaining what this is and how to use it.

I noticed that the various switches for turning on/off Additional Stats & Charts are removed and that all the stats now show up in the drop box in the dashboard. What was good about the old way was that one would get a list showing various stats under each other. The new way one has to select in the drop down for the specific stat and only view that. There is no way to set a Sessions, Users, Location and searches for them all to show up under each other (as in the old view way). It would perhaps be nice with a tab under tracking with checkboxes with something like: Have stat boxes show up under eachother in the Dashboard and not just in the dropdown box. Then list the stats. Or something like this...

**Comment by deconf** [comment]
Some are fixed on 4.5, I've just implemented one (ON = disable, is bad UX). There are other few props ^^ that will indeed improve UX.

Thanks for your contribution!

**Comment by paaljoachim** [comment]
Your welcome! I am happy to make your plugin better. I also plan on creating a video tutorial. Hopefully you'll add some additional helpful links to the sections that have features that are not intuitive to understand.

**Comment by paaljoachim** [comment]
Backend Settings and Frontend Settings titles have changed to Permissions.

Tracking code section.
Here it would be nice with a click to documentation of what it is. What is it? I can always add various information to this article: http://easywebdesigntutorials.com/google-analytics-dashboard-for-wp-plugin/

I also plan on creating a video tutorial, and the more info you give me for each page the more I can also add to the article and to the video tutorial.

Exclude Tracking. It would be nice if Administrator was at default checked. As it can sometimes be easy to forget to click the checkbox to turn it on.

Good job with the plugin!

**Comment by deconf** [comment]
Well, excluding tracking by default for Administrators leads to a ton of support questions because they are trying to see if the code is inserted in the webpage while logged in.

Since I've unchecked that by default, there were no more questions about tracking code missing.

**Comment by paaljoachim** [comment]
Ahh I understand.
Btw I checked your web site and noticed a few people ask about viewing multiple stats at the same time (as it was earlier) without having to view one stat at a time. I am looking forward to you also finding a solution to this. Have a great continued Easter. Let me know if you want me to add some additional information to the blog post.
