### ISSUE TITLE
Exclude Tracking by IP Address

### ISSUE THREAD

**Issue by prasetyop** [deconf/Google-Analytics-Dashboard-for-WP#93]
Hi, Thanks for a great plugin. Just wondering if we can exclude tracking by IP addresses, I know we can exclude from google analytics but would be nice if we have that options on WP backend.

Thanks

**Comment by deconf** [comment]
Hi,

I'm trying not to mix features between the plugin itself and the service. If the feature is provided by the service won't be implemented in the plugin.
