### ISSUE TITLE
No Google analytics dashboard on Wordpress dashboard

### ISSUE THREAD

**Issue by webcreation-bzh** [deconf/Google-Analytics-Dashboard-for-WP#94]
Hi,

I have no more Google analytics dashboard on the Wordpress dashboard (it was working before).
I have no error.
![tableau de bord google analytics](https://cloud.githubusercontent.com/assets/8410095/24800772/ccb6f888-1ba1-11e7-83b7-371f7eb0f1ea.PNG)
![erreur google analytics](https://cloud.githubusercontent.com/assets/8410095/24800776/d0b9319e-1ba1-11e7-8be2-475f99b8474a.PNG)

Can you help me please.

**Comment by deconf** [comment]
Hi,

Most probably it's a JavaScript error, for details check the [FAQ Page](https://deconf.com/faq-about-google-analytics-dashboard-for-wordpress/).
