### ISSUE TITLE
Invalid Response with no error information

### ISSUE THREAD

**Issue by Edvino79** [deconf/Google-Analytics-Dashboard-for-WP#96]
After the WP update earlier this week the dashboard widget is not showing a graph anymore but is shows a lot of data and a message at the top: Invalid Response.
The error & debug section is not showing any error details.

**Comment by deconf** [comment]
Hi,
GADWP 4.9.6.2 and 5.0 are tested with the latest version. We can't replicate the issue. Try to clear your cache amd check for plugin conflicts, here's a list with the faq: https://deconf.com/google-analytics-dashboard-for-wp-documentation-table-of-contents/, where you can find information on how to do these.
