### ISSUE TITLE
Allow custom labels when tracking form submit

### ISSUE THREAD

**Issue by tschneid** [deconf/Google-Analytics-Dashboard-for-WP#98]
First of all, the feature to track form submission is great! However, we got several contact forms on our website, which can only be distinguished in GA by the `value` of the submit button (which is the text shown on the button, mostly "send"). Thus, I suggest giving the possibility to define custom attributes and/or use the `name` attribute on the submit button for the label of the tracked event.

This is the [code of interest](https://github.com/deconf/Google-Analytics-Dashboard-for-WP/blob/bfa4561ec211b13c357b129e91d2c9b922371571/front/js/tracking-analytics-events.js#L144):
```js
gadwpSubmitObject = this;
var label = gadwpSubmitObject.value;
...
ga( 'send', 'event', 'form', 'submit', label );
```

With a custom attribute `ga-label` and the `name` attribute (and fallback to `value`), the code would look like this:
```js
var label = gadwpSubmitObject.getAttribute('ga-label') || gadwpSubmitObject.name || gadwpSubmitObject.value;
```

IMHO the custom attribute is the cleanest solution, but might not be settable from plugins like CF7. In CF7 however one can set the `name` attribute with `html_name="foo"`.

What do you think?
Are there any other solutions to this that I'm missing? :)

**Comment by deconf** [comment]
Nice idea!
The **ga-label** will be **data-ga-label**. Even if the name should be first taken in account, for compatibility with older versions I may have to prioritize the value.

Thanks for the feedback!

**Comment by tschneid** [comment]
Nice! Thanks for your work!
