### ISSUE TITLE
I have reauthorize with google every now and then

### ISSUE THREAD

**Issue by joransrb** [deconf/Google-Analytics-Dashboard-for-WP#99]
Hey,

Using the latest version available from the wordpress repository,
every now and then i have reauthorize with google, it seems like it "times out" the authorization.

ill try and investigate a bit more, since i just discorvered it.

Cheers

**Comment by deconf** [comment]
Hi,

See https://deconf.com/error-refreshing-the-oauth2-token-message-error-invalid_grant/
